# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
flutter_application_path = '../flutter_app/'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

target 'iOS_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_app

end

stuffed_str = """
<dict>
  <key>io.flutter.embedded_views_preview</key>
  <true/>"""

runner_infoplist = flutter_application_path + '.ios/Runner/info.plist'
original_content = File.read(runner_infoplist)

unless original_content.include?("io.flutter.embedded_views_preview")
  new_content = original_content.gsub("<dict>", stuffed_str)
  File.open(runner_infoplist, 'w') { |file| file.puts new_content }
end
